sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 121911
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tJcJLh6cy33jfYWQayw
    access-key-secret: dIL8rX1aRzig9SHDozUOMJYdRz9ULG
    bucket-name: web-tlias-lijing
  redis:
    host: 192.168.236.128
    port: 6379
    password: 121911
    database: 0

